version: '3'
services:
  gocd_server:
    image: "gocd/gocd-server:v17.3.0"
    ports:
      - "8153:8153"
      - "8154:8154"
    links:
      - gocd_agent_ubuntu

  gocd_agent_ubuntu:
    image: "gocd/gocd-agent-ubuntu-16.04:v17.11.0"
    environment:
      - GO_SERVER_URL=https://gocd_server:8154/go
    volumes:
      - ./godata:/godata
      - ./go:/home/go

  jenkins_ci:
    image: "jenkinsci/blueocean"
    ports:
      - "8080:8080"

  sonarqube:
    image: "sonarqube:5.6.6-alpine"
    ports:
      - "9000:9000"
      - "9092:9092"
    links:
      - gocd_agent_ubuntu

networks:
  default:
    driver: bridge
    driver_opts:
      com.docker.network.driver.mtu: 1450
